server:
  port: 9000
spring:
  application:
    name: spring-lb-invoker
default:
  ribbon:
    NFLoadBalancerRuleClassName: org.crazyit.cloud.MyRule
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/